# docker-compose.yml
version: '3'
services:

  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - ../laravel:/app

  php:
    image: php:8.0.3-cli
    volumes:
      - ../laravel:/app
    working_dir: /app
    links:
      - mysql

  phpunit:
    image: php:8.0.3-cli
    volumes:
      - ../laravel:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

  fpm:
    image: php:8.0.3-fpm
    restart: always
    volumes:
      - ../laravel:/app

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ../laravel:/app
      - ./nginx:/var/log/nginx
      - ./nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=Default-Root-Password
    volumes:
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/