services:
  php:
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    volumes:
      - ./:/app:ro
      - ./php/caddy_dev.Caddy
    ports:
      - "80:80"

  database:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: []

volumes:
  pgdata:
