; Habilitar extensión (la instala install-php-extensions)
zend_extension=xdebug

; Modos recomendados en desarrollo (puedes sobrescribir por env con XDEBUG_MODE)
xdebug.mode=develop,debug

; Iniciar depuración al recibir cookie/param o según el IDE (nunca “always” en equipos)
xdebug.start_with_request=trigger

; Dónde enviar las conexiones de depuración (desde contenedor -> host)
xdebug.client_host=host.docker.internal
xdebug.client_port=9003

; Mejor traza de errores en desarrollo
xdebug.log_level=0
;xdebug.log=/tmp/xdebug.log

; Tiempo de espera (útil si el IDE tarda en enganchar)
xdebug.connect_timeout_ms=2000

; IDE key (opcional)
xdebug.idekey=PHPSTORM
